from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.urls import reverse
from .forms import PatientRecordForm, VisitLogForm
from .models import PatientRecord
from django.core.paginator import Paginator
from django.db.models import Q   # ✅ needed for search queries


from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def is_doctor_or_admin(user):
    return user.is_authenticated and hasattr(user, 'profile') and user.profile.role in ['doctor', 'admin']

@login_required
@user_passes_test(is_doctor_or_admin)
def download_patient_pdf(request, pk):
    record = get_object_or_404(PatientRecord, pk=pk)

    # Create PDF response
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="Patient_{record.patient_code}.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    p.setFont("Helvetica", 12)

    # Header
    p.drawString(100, 750, f"Patient Record - {record.patient_code}")
    p.line(100, 745, 500, 745)

    # Patient details
    p.drawString(100, 720, f"Full Name: {record.full_name}")
    p.drawString(100, 700, f"Date of Birth: {record.date_of_birth or 'N/A'}")
    p.drawString(100, 680, f"Age: {record.age or 'N/A'}")
    p.drawString(100, 660, f"Gender: {record.get_gender_display()}")
    p.drawString(100, 640, f"Department: {record.department}")
    p.drawString(100, 620, f"Attending Physician: {record.attending_physician.get_full_name() if record.attending_physician else 'N/A'}")
    p.drawString(100, 600, f"Created At: {record.created_at.strftime('%Y-%m-%d %H:%M')}")

    # Footer
    p.drawString(100, 560, "Generated by HPIS System")

    p.showPage()
    p.save()

    return response





@never_cache
@login_required
@user_passes_test(is_doctor_or_admin)
def create_patient_record(request):
    if request.method == 'POST':
        form = PatientRecordForm(request.POST, request.FILES)
        if form.is_valid():
            record = form.save(commit=False)

            # If the user is a doctor and physician not selected, assign current user
            if hasattr(request.user, 'profile') and request.user.profile.role == 'doctor' and not record.attending_physician:
                record.attending_physician = request.user

            record.save()
            return redirect('patient_record_detail', pk=record.pk)
        else:
            return render(request, 'records/create_patient.html', {'form': form})
    else:
        initial_data = {}
        if hasattr(request.user, 'profile') and request.user.profile.role == 'doctor':
            initial_data['attending_physician'] = request.user

        form = PatientRecordForm(initial=initial_data)
        return render(request, 'records/create_patient.html', {'form': form})


@login_required
@user_passes_test(is_doctor_or_admin)
def update_patient_record(request, pk):
    record = get_object_or_404(PatientRecord, pk=pk)

    if request.method == 'POST':
        form = PatientRecordForm(request.POST, request.FILES, instance=record)
        if form.is_valid():
            # Doctors can only update if they are the attending physician
            if request.user.profile.role == 'doctor' and request.user != record.attending_physician:
                messages.error(request, "Permission denied: you are not the attending physician.")
                return redirect('patient_record_detail', pk=record.pk)

            form.save()
            return redirect('patient_record_detail', pk=record.pk)
    else:
        form = PatientRecordForm(instance=record)

    context = {
        'form': form,
        'record': record,
    }
    return render(request, 'records/create_patient.html', context)


@login_required
@user_passes_test(is_doctor_or_admin)
def patient_record_detail(request, pk):
    record = get_object_or_404(PatientRecord, pk=pk)
    context = {
        'record': record,
    }
    return render(request, 'records/patient_record_detail.html', context)


@login_required
@user_passes_test(is_doctor_or_admin)
def add_visit_log(request, pk):
    patient = get_object_or_404(PatientRecord, pk=pk)

    if request.method == 'POST':
        log_form = VisitLogForm(request.POST)
        if log_form.is_valid():
            visit_log = log_form.save(commit=False)
            visit_log.patient = patient
            visit_log.clinician = request.user
            visit_log.save()
            return redirect('patient_record_detail', pk=patient.pk)
    else:
        log_form = VisitLogForm()

    context = {
        'patient': patient,
        'log_form': log_form,
        # assumes VisitLog model has related_name='visit_history'
        'recent_logs': patient.visit_history.all()[:3],
    }
    return render(request, 'records/add_visit_log.html', context)


@login_required
@user_passes_test(is_doctor_or_admin)
def records_list(request):
    queryset = PatientRecord.objects.all().select_related('attending_physician').order_by('-created_at')

    # Doctors only see their own patients
    if request.user.profile.role == 'doctor':
        queryset = queryset.filter(attending_physician=request.user)

    # --- Search & Filter ---
    search_query = request.GET.get('search', '')
    department_filter = request.GET.get('department', '')

    if search_query:
        queryset = queryset.filter(
            Q(full_name__icontains=search_query) |
            Q(attending_physician__username__icontains=search_query) |
            Q(patient_code__icontains=search_query)
        )

    if department_filter:
        queryset = queryset.filter(department=department_filter)

    # --- Pagination ---
    paginator = Paginator(queryset, 10)  # 10 records per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'records': page_obj,
        'search_query': search_query,
        'department_filter': department_filter,
        'page_obj': page_obj,
    }
    return render(request, 'records/records_list.html', context)