# Generated by Django 5.2.7 on 2025-12-06 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_alter_accesslog_access_type_and_more'),
        ('records', '0007_alter_patientrecord_patient_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Generic medicine name', max_length=255)),
                ('brand_name', models.CharField(blank=True, help_text='Brand/trade name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the medicine')),
                ('category', models.CharField(blank=True, db_index=True, help_text='e.g., Antibiotic, Analgesic, Antipyretic', max_length=100)),
                ('dosage_form', models.CharField(blank=True, help_text='e.g., Tablet, Syrup, Capsule, Ointment, Injection', max_length=100)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 5mg/mL', max_length=100)),
                ('unit', models.CharField(default='tablet', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Minimum quantity before reorder alert')),
                ('storage_instructions', models.TextField(blank=True, help_text='Storage temperature, conditions, etc.')),
                ('prescription_only', models.BooleanField(default=False, help_text='True if prescription required, False for OTC')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Out of Stock', 'Out of Stock'), ('Expired', 'Expired'), ('Discontinued', 'Discontinued')], db_index=True, default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory_meds.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stock_before', models.PositiveIntegerField(default=0)),
                ('stock_after', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to='main.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='records.patientrecord')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='main.userprofile')),
                ('visit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to='records.visitlog')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='inventory_meds.medicine')),
            ],
            options={
                'ordering': ['-dispensed_at', '-id'],
                'indexes': [models.Index(fields=['medicine', 'dispensed_at'], name='inventory_m_medicin_af6acb_idx'), models.Index(fields=['patient', 'dispensed_at'], name='inventory_m_patient_65a125_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicineAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ARCHIVE', 'Archived'), ('STOCK_ADD', 'Stock Added'), ('STOCK_REDUCE', 'Stock Reduced'), ('DISPENSE', 'Dispensed'), ('ACCESS_DENIED', 'Access Denied')], db_index=True, max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory_meds.medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_audit_logs', to='main.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='inventory_m_action_7d43b2_idx'), models.Index(fields=['medicine', 'timestamp'], name='inventory_m_medicin_bcc0f8_idx'), models.Index(fields=['user', 'timestamp'], name='inventory_m_user_id_d6a11f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Received'), ('OUT', 'Dispensed'), ('ADJUST', 'Adjusted')], db_index=True, max_length=10)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory_meds.medicine')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='main.userprofile')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['movement_type', 'performed_at'], name='inventory_m_movemen_81f1bd_idx'), models.Index(fields=['medicine', 'performed_at'], name='inventory_m_medicin_448465_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name', 'category'], name='inventory_m_name_2d8985_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expires_on'], name='inventory_m_expires_5c9302_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['batch_number'], name='inventory_m_batch_n_21fadd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['status'], name='inventory_m_status_90e801_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('name', 'dosage_form', 'strength', 'batch_number'), name='unique_medicine_batch'),
        ),
    ]
