# Generated by Django 5.2.7 on 2025-12-03 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_meds', '0001_initial'),
        ('main', '0006_alter_accesslog_access_type_and_more'),
        ('records', '0008_alter_patientrecord_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ARCHIVE', 'Archived'), ('STOCK_ADD', 'Stock Added'), ('STOCK_REDUCE', 'Stock Reduced'), ('DISPENSE', 'Dispensed'), ('ACCESS_DENIED', 'Access Denied')], db_index=True, max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='stock_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='stock_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand/trade name', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_only',
            field=models.BooleanField(default=False, help_text='True if prescription required, False for OTC'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Out of Stock', 'Out of Stock'), ('Expired', 'Expired'), ('Discontinued', 'Discontinued')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_instructions',
            field=models.TextField(blank=True, help_text='Storage temperature, conditions, etc.'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., Antibiotic, Analgesic, Antipyretic', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., Tablet, Syrup, Capsule, Ointment, Injection', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, help_text='Generic medicine name', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum quantity before reorder alert'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 5mg/mL', max_length=100),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['batch_number'], name='inventory_m_batch_n_21fadd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['status'], name='inventory_m_status_90e801_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('name', 'dosage_form', 'strength', 'batch_number'), name='unique_medicine_batch'),
        ),
        migrations.AddField(
            model_name='medicineauditlog',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory_meds.medicine'),
        ),
        migrations.AddField(
            model_name='medicineauditlog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.patientrecord'),
        ),
        migrations.AddField(
            model_name='medicineauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_audit_logs', to='main.userprofile'),
        ),
        migrations.AddIndex(
            model_name='medicineauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='inventory_m_action_7d43b2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineauditlog',
            index=models.Index(fields=['medicine', 'timestamp'], name='inventory_m_medicin_bcc0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='inventory_m_user_id_d6a11f_idx'),
        ),
    ]
