# Generated by Django 5.2.7 on 2025-11-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_patientrecord_allergies_patientrecord_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='vitals',
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('vitals', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='records.patientrecord')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
