# Generated by Django 5.2.7 on 2025-11-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_patientrecord_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='attending_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
