# Generated by Django 5.2.7 on 2025-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_patientrecord_attending_physician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='patient_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
