# Generated by Django 5.2.7 on 2025-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_generate_patient_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
