# Generated by Django 5.2.7 on 2025-11-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filters',
        ),
    ]
