# Generated by Django 5.2.7 on 2025-12-03 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_report_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[('login', 'Login'), ('data_view', 'Data View'), ('data_update', 'Data Update'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('data_download', 'Data Download')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'General Consultation'), ('followup', 'Follow-up'), ('checkup', 'Routine Checkup'), ('emergency', 'Emergency')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Doctor'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('doctor', 'Doctor')], db_index=True, default='doctor', max_length=20),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', '-timestamp'], name='main_access_user_id_001b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_type', '-timestamp'], name='main_access_access__d0df22_idx'),
        ),
        migrations.AddIndex(
            model_name='patientappointment',
            index=models.Index(fields=['status', 'appointment_date'], name='main_patien_status_cb006c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientappointment',
            index=models.Index(fields=['assigned_doctor', 'status'], name='main_patien_assigne_b5060c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientappointment',
            index=models.Index(fields=['-created_at'], name='main_patien_created_035d95_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'department'], name='main_userpr_role_b0bb63_idx'),
        ),
    ]
