# Generated by Django 5.2.7 on 2025-12-06 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='inventory.medicine')),
            ],
            options={
                'indexes': [models.Index(fields=['dispensed_at'], name='inventory_d_dispens_0f592f_idx'), models.Index(fields=['patient_id', 'dispensed_at'], name='inventory_d_patient_56d908_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.medicine')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['medicine', 'timestamp'], name='inventory_s_medicin_4dd52b_idx'), models.Index(fields=['movement_type', 'timestamp'], name='inventory_s_movemen_80a98d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='inventory_m_name_7f2fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active', 'expiration_date'], name='inventory_m_is_acti_f130d1_idx'),
        ),
    ]
